[project]
name = "panel-neuroglancer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "neuroglancer>=2.40.1",
    "panel>=1.5.4",
]
